name: python-pep8

on: [push, pull_request]

jobs:
  check-pep8:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install flake8
      - name: Run checking
        run: |
          flake8 .
